[network]
port = 30303
interface = "0.0.0.0"
nat = "extip:127.0.0.1"

[parity]
chain = "ethereum"
base_path = "/openethereum/data"

[rpc]
port = 8545
interface = "0.0.0.0"
cors = ["all"]
apis = ["safe"]
hosts = ["all"]

[websockets]
port = 8546
interface = "0.0.0.0"
origins = ["all"]
apis = ["safe"]
hosts = ["all"]

[ipc]
disable = false
apis = ["all"]