version: "3.3"

services:
  openethereum:
    image: openethereum
    build:
      context: .
    container_name: openethereum
    expose:
      - 8545
      - 8546
      - 30303
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    restart: always
    volumes:
      - ./data:/home/openethereum/data
      - ./config.toml:/home/openethereum/config.toml
    command: --config /home/openethereum/config.toml
