version: "3.3"

services:
  openethereum:
    image: openethereum/openethereum:latest
    container_name: openethereum
    expose:
      - 8545
      - 8546
    ports:
      - 8545:8545
      - 8546:8546
    restart: always
    volumes:
      - ./data:/data/openethereum
      - ./config.toml:/home/openethereum/config.toml
    command: --config /home/openethereum/config.toml
